name: "Fines_Serial"
version: "0.1.0"
description: "Serial port communication driver"
maintainers:
  - name: "fins"
    email: "fins@sjtu.edu.cn"
depends:
  geometry_msgs: "system"
  fmt: "9.1.0"
licenses:
  - "MIT"